ALTER TABLE category ADD COLUMN created TIMESTAMP DEFAULT NOW();
ALTER TABLE category ADD COLUMN updated TIMESTAMP DEFAULT NOW();

ALTER TABLE catalog ADD COLUMN created TIMESTAMP DEFAULT NOW();
ALTER TABLE catalog ADD COLUMN updated TIMESTAMP DEFAULT NOW();

ALTER TABLE catalog_block ADD COLUMN created TIMESTAMP DEFAULT NOW();
ALTER TABLE catalog_block ADD COLUMN updated TIMESTAMP DEFAULT NOW();

ALTER TABLE image ADD COLUMN created TIMESTAMP DEFAULT NOW();
ALTER TABLE image ADD COLUMN updated TIMESTAMP DEFAULT NOW();

ALTER TABLE text ADD COLUMN created TIMESTAMP DEFAULT NOW();
ALTER TABLE text ADD COLUMN updated TIMESTAMP DEFAULT NOW();
